# Generated by Django 5.0.3 on 2024-03-19 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('chips', models.IntegerField()),
                ('cards', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='table',
            old_name='players',
            new_name='players_number',
        ),
        migrations.CreateModel(
            name='CommunityCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.CharField(max_length=15)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.table')),
            ],
        ),
        migrations.CreateModel(
            name='TableInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.table')),
            ],
        ),
    ]
