# Generated by Django 5.0.3 on 2024-03-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_rename_players_table_players_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='tables', to='game.player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='chips',
            field=models.IntegerField(default=10000),
        ),
        migrations.DeleteModel(
            name='TableInfo',
        ),
    ]
