# Generated by Django 5.0.3 on 2024-04-03 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='players',
        ),
        migrations.AlterField(
            model_name='seat',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.player'),
        ),
    ]
