# Generated by Django 5.0.3 on 2024-04-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_table_players_alter_seat_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='cards',
            new_name='hand',
        ),
        migrations.AddField(
            model_name='table',
            name='deck',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
