# Generated by Django 5.0.3 on 2024-04-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_rename_cards_player_hand_table_deck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='hand',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
