# Generated by Django 5.0.3 on 2024-04-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_player_hand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='hand',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
