# Generated by Django 5.0.3 on 2024-04-04 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_table_dealer_button'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='dealer_button',
            new_name='dealer',
        ),
    ]
